server.port: 8010
spring.datasource.url: jdbc:mysql://localhost:3306/blog_site?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
spring.datasource.username: root
spring.datasource.password: 23019088
spring.jpa.hibernate.ddl-auto:
spring.main.allow-bean-definition-overriding: true

intervalCountTime: 1

spring.security.user.name: admin
spring.security.user.password: 12345

spring.mail.host: smtp.yandex.ru
spring.mail.username: your_email
spring.mail.password: your_password
spring.mail.port: 465
spring.mail.protocol: smtps
mail.debug: true


